package niel.kro.penik.data.crypto

import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.junit.Assert.*
import org.junit.BeforeClass
import org.junit.Test
import java.security.Security

/**
 * Cross-platform wire compatibility test verifying that Android's legacy Java/BouncyCastle
 * crypto implementation seamlessly interoperates with the new Rust/WASM crypto core.
 */
class CrossPlatformWireCompatTest {

    companion object {
        @BeforeClass
        @JvmStatic
        fun setup() {
            Security.removeProvider("BC")
            Security.addProvider(BouncyCastleProvider())
        }
    }

    private val crypto = E2EECrypto()

    @Test
    fun testAndroidDecryptsMessageEncryptedByRustWasm() {
        // Keys generated by Rust / WebAssembly
        val alicePriv = ByteArray(32) { 1 }
        val bobPriv = ByteArray(32) { 2 }
        val alicePub = byteArrayOf(
            164.toByte(), 224.toByte(), 146.toByte(), 146.toByte(), 182.toByte(), 81, 194.toByte(), 120,
            185.toByte(), 119, 44, 86, 159.toByte(), 95, 169.toByte(), 187.toByte(),
            19, 217.toByte(), 6, 180.toByte(), 106, 182.toByte(), 140.toByte(), 157.toByte(),
            249.toByte(), 220.toByte(), 43, 68, 9, 248.toByte(), 162.toByte(), 9
        )
        val bobPub = byteArrayOf(
            206.toByte(), 141.toByte(), 58, 209.toByte(), 204.toByte(), 182.toByte(), 51, 236.toByte(),
            123, 112, 193.toByte(), 120, 20, 165.toByte(), 199.toByte(), 110,
            205.toByte(), 2, 150.toByte(), 133.toByte(), 5, 13, 52, 71,
            69, 186.toByte(), 5, 135.toByte(), 14, 88, 125, 89
        )

        // Verify shared secret derivation matches Rust
        val bobSharedSecret = crypto.deriveSharedSecret(bobPriv, alicePub)
        val expectedSecret = byteArrayOf(
            46, 215.toByte(), 106, 181.toByte(), 73, 177.toByte(), 231.toByte(), 60,
            3, 30, 180.toByte(), 156.toByte(), 148.toByte(), 72, 240.toByte(), 121,
            138.toByte(), 234.toByte(), 129.toByte(), 182.toByte(), 152.toByte(), 39, 154.toByte(), 12,
            61, 195.toByte(), 228.toByte(), 159.toByte(), 191.toByte(), 196.toByte(), 185.toByte(), 83
        )
        assertArrayEquals("Diffie-Hellman secret must match Rust", expectedSecret, bobSharedSecret)

        // Ciphertext produced by Rust penik-crypto
        val salt = byteArrayOf(
            121, 158.toByte(), 195.toByte(), 32, 163.toByte(), 63, 78, 177.toByte(),
            181.toByte(), 113, 72, 27, 67, 172.toByte(), 138.toByte(), 133.toByte(),
            123, 208.toByte(), 129.toByte(), 63, 57, 210.toByte(), 148.toByte(), 236.toByte(),
            250.toByte(), 238.toByte(), 216.toByte(), 166.toByte(), 125, 31, 77, 105
        )
        val nonce = byteArrayOf(218.toByte(), 131.toByte(), 113, 23, 79, 76, 129.toByte(), 246.toByte(), 107, 0, 61, 107)
        val ciphertext = byteArrayOf(
            188.toByte(), 114, 218.toByte(), 74, 97, 231.toByte(), 213.toByte(), 165.toByte(),
            164.toByte(), 218.toByte(), 106, 42, 4, 111, 24, 29,
            200.toByte(), 206.toByte(), 121, 78, 67, 196.toByte(), 144.toByte(), 27,
            172.toByte(), 71, 123, 114, 249.toByte(), 125, 187.toByte(), 84,
            49, 116, 188.toByte(), 112, 75, 124, 249.toByte(), 227.toByte()
        )

        // Build AAD using Android implementation
        val aad = crypto.buildPairwiseAad(10L, 20L, "msg-cross-1", 1700000000L)

        // Decrypt with Android legacy crypto
        val decrypted = crypto.decrypt(ciphertext, bobSharedSecret, salt, nonce, aad = aad)
        val decryptedText = String(decrypted, Charsets.UTF_8)

        assertEquals("Hello Android from Rust!", decryptedText)
    }

    @Test
    fun testSafetyNumberMatchesRustExact() {
        val alicePub = byteArrayOf(
            164.toByte(), 224.toByte(), 146.toByte(), 146.toByte(), 182.toByte(), 81, 194.toByte(), 120,
            185.toByte(), 119, 44, 86, 159.toByte(), 95, 169.toByte(), 187.toByte(),
            19, 217.toByte(), 6, 180.toByte(), 106, 182.toByte(), 140.toByte(), 157.toByte(),
            249.toByte(), 220.toByte(), 43, 68, 9, 248.toByte(), 162.toByte(), 9
        )
        val bobPub = byteArrayOf(
            206.toByte(), 141.toByte(), 58, 209.toByte(), 204.toByte(), 182.toByte(), 51, 236.toByte(),
            123, 112, 193.toByte(), 120, 20, 165.toByte(), 199.toByte(), 110,
            205.toByte(), 2, 150.toByte(), 133.toByte(), 5, 13, 52, 71,
            69, 186.toByte(), 5, 135.toByte(), 14, 88, 125, 89
        )

        val androidNumber = SafetyNumber.compute(alicePub, bobPub)
        assertEquals("24939 22235 19566 19126 43519", androidNumber)

        val androidHex = SafetyNumber.computeFingerprintHex(listOf(alicePub), listOf(bobPub))
        assertEquals("616b56db4c6e4ab6a9ffe1e584827a359fcf847c9fa5174c7853d04066f5187f", androidHex)

        val androidWords = SafetyNumber.computeWords(alicePub, bobPub)
        val expectedWords = listOf("зубр", "исток", "запад", "опал", "дюна", "кадет", "доспех", "магнит", "лилия", "прибой")
        assertEquals(expectedWords, androidWords)
    }
}
