// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function HttpBinaryRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HttpBinaryRequest'](arg1, arg2, arg3, arg4);
}

export function HttpRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HttpRequest'](arg1, arg2, arg3, arg4);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
