// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDeviceName():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetServerURL():Promise<string>;

export function GetVersionInfo():Promise<main.VersionInfo>;

export function Hide():Promise<void>;

export function HttpRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<main.HttpResponse>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<main.FileFilter>):Promise<string>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<main.FileFilter>):Promise<string>;

export function SetServerURL(arg1:string):Promise<void>;

export function Show():Promise<void>;

export function ToggleWindow():Promise<void>;
